name: Publish

on:
  workflow_dispatch:

concurrency: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2

    - name: Gradle Validation
      timeout-minutes: 1
      uses: gradle/wrapper-validation-action@v1

    - name: Set up Java
      timeout-minutes: 1
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 15

    - name: Publish
      timeout-minutes: 10
      env:
        ORG_GRADLE_PROJECT_twofortyfouramMonorepoMavenUrl: https://maven.pkg.github.com/twofortyfouram/android-monorepo
        ORG_GRADLE_PROJECT_twofortyfouramMonorepoMavenUser: ${{ github.actor }}
        ORG_GRADLE_PROJECT_twofortyfouramMonorepoMavenToken: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_isCoverageEnabled: false
      run: |
        ./gradlew publish
