name: Publish

on:
  workflow_dispatch:

concurrency: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2

    - name: Setup
      id: setup
      timeout-minutes: 5
      uses: ./.github/actions/setup

    - name: Publish
      timeout-minutes: 10
      env:
        ORG_GRADLE_PROJECT_twofortyfouramMonorepoMavenUrl: ${{ format('https://maven.pkg.github.com/{0}', github.repository) }}
        ORG_GRADLE_PROJECT_twofortyfouramMonorepoMavenUser: ${{ github.actor }}
        ORG_GRADLE_PROJECT_twofortyfouramMonorepoMavenToken: ${{ secrets.GITHUB_TOKEN }}
        ORG_GRADLE_PROJECT_isCoverageEnabled: false
      run: |
        ./gradlew publish --no-daemon
