# Expected Secrets
# GCLOUD_JSON_KEY_BASE_64

name: Pull Request

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/dependabot.yml'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.github/ISSUE_TEMPLATE/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2

    - name: Setup
      id: setup
      timeout-minutes: 5
      uses: ./.github/actions/setup

    - name: Setup Secrets
      env:
        FIREBASE_TEST_LAB_API_KEY_BASE_64: ${{ secrets.GCLOUD_JSON_KEY_BASE_64 }}
        GCLOUD_KEY_FILE_PATH: ${{ format('{0}/gcloud-key.json', env.home) }}
      run: |
           echo $FIREBASE_TEST_LAB_API_KEY_BASE_64 | base64 --decode > ${GCLOUD_KEY_FILE_PATH}

    - name: Build
      timeout-minutes: 15
      env:
        ORG_GRADLE_PROJECT_isCoverageEnabled: false
      run: |
        ./gradlew assembleDebug assembleAndroidTest --no-daemon

    - name: Test
      timeout-minutes: 20
      env:
        ORG_GRADLE_PROJECT_isCoverageEnabled: false
        ORG_GRADLE_PROJECT_twofortyfouramFirebaseTestLabServiceAccountKeyPath: ${{ format('{0}/gcloud-key.json', env.home) }}
      run: |
        ./gradlew runFlank --no-daemon --parallel --stacktrace

    - name: Collect Artifacts
      timeout-minutes: 1
      env:
        ARTIFACTS_DIR_PATH: ${{ format('{0}/artifacts', env.home) }}
        TEST_RESULTS_FILE_PATH: ${{ format('{0}/artifacts/test_results.zip', env.home) }}
      run: |
        mkdir ${ARTIFACTS_DIR_PATH}

        zip -r ${TEST_RESULTS_FILE_PATH} . -i *build/outputs/androidTest-results/*

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      timeout-minutes: 1
      with:
        name: Test results
        path: ~/artifacts