# Expected Secrets
# Note that these values aren't really secret since they configure Workload Identity Federation,
# however passing them in as "secrets" simplifies providing these environment variables in a
# configurable way.
# FIREBASE_TEST_LAB_PROJECT - Name of the Firebase Test Lab project
# FIREBASE_TEST_LAB_SERVICE_ACCOUNT - Email address of the Firebase
# FIREBASE_TEST_LAB_WORKLOAD_IDENTITY_PROVIDER -

name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.github/dependabot.yml'
      - 'LICENSE'
      - 'README.md'
      - 'docs/**'

jobs:
  validate_gradle_wrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v2.4.0
      # Gradle Wrapper validation can be flaky
      # https://github.com/gradle/wrapper-validation-action/issues/40
      - name: Gradle Wrapper Validation
        timeout-minutes: 1
        uses: gradle/wrapper-validation-action@v1.0.4

  check_secrets:
    runs-on: ubuntu-latest
    outputs:
      has-secrets: ${{ steps.check_secrets.outputs.defined }}
    steps:
      - id: check_secrets
        env:
          FIREBASE_TEST_LAB_PROJECT: ${{ secrets.FIREBASE_TEST_LAB_PROJECT }}
          FIREBASE_TEST_LAB_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_TEST_LAB_SERVICE_ACCOUNT }}
          FIREBASE_TEST_LAB_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.FIREBASE_TEST_LAB_WORKLOAD_IDENTITY_PROVIDER }}
        if: "${{ env.FIREBASE_TEST_LAB_PROJECT != '' && env.FIREBASE_TEST_LAB_SERVICE_ACCOUNT != '' && env.FIREBASE_TEST_LAB_WORKLOAD_IDENTITY_PROVIDER != '' }}"
        run: echo "::set-output name=defined::true"

  test_android_modules:
    needs: [validate_gradle_wrapper, check_secrets]
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2

    - name: Setup
      id: setup
      timeout-minutes: 5
      uses: ./.github/actions/setup

    - name: Build
      timeout-minutes: 15
      env:
        ORG_GRADLE_PROJECT_isCoverageEnabled: false
      run: |
        ./gradlew assembleDebug assembleAndroidTest

    - name: Authenticate to Google Cloud for Firebase Test Lab
      id: auth_test_lab
      uses: google-github-actions/auth@v0.6.0
      with:
        create_credentials_file: true
        project_id: ${{ secrets.FIREBASE_TEST_LAB_PROJECT }}
        service_account: ${{ secrets.FIREBASE_TEST_LAB_SERVICE_ACCOUNT }}
        workload_identity_provider: ${{ secrets.FIREBASE_TEST_LAB_WORKLOAD_IDENTITY_PROVIDER }}
        access_token_lifetime: '1200s'

    - name: Test
      timeout-minutes: 20
      env:
        ORG_GRADLE_PROJECT_isCoverageEnabled: false
        # This is used by Flank, since the temporary token is missing the project name
        GOOGLE_CLOUD_PROJECT: ${{ secrets.FIREBASE_TEST_LAB_PROJECT }}
        ORG_GRADLE_PROJECT_twofortyfouramFirebaseTestLabServiceAccountKeyPath: ${{ steps.auth_test_lab.outputs.credentials_file_path }}
      run: |
        ./gradlew runFlank

    - name: Collect Artifacts
      timeout-minutes: 1
      env:
        ARTIFACTS_DIR_PATH: ${{ format('{0}/artifacts', env.home) }}
        TEST_RESULTS_FILE_PATH: ${{ format('{0}/artifacts/test_results.zip', env.home) }}
      run: |
        mkdir ${ARTIFACTS_DIR_PATH}

        zip -r ${TEST_RESULTS_FILE_PATH} . -i *build/outputs/androidTest-results/* build/fladle/*

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      timeout-minutes: 1
      with:
        name: Test results
        path: ~/artifacts
